# Generated by Django 5.0 on 2025-09-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_Q_and_A_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_chat_group_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_lesson_notes_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
