# Generated by Django 5.0 on 2025-09-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_client_is_q_and_a_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='index_page',
            field=models.CharField(choices=[('home', 'home'), ('login', 'login')], default='home', max_length=255),
        ),
    ]
