# Generated by Django 5.0 on 2025-09-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_client_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_text',
            field=models.CharField(blank=True, choices=[('logo', 'logo'), ('text', 'text')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_type',
            field=models.CharField(choices=[('logo', 'logo'), ('text', 'text')], default='logo', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='index_page',
            field=models.CharField(choices=[('home', 'home'), ('login', 'login'), ('courses', 'courses')], default='home', max_length=255),
        ),
    ]
