# Generated by Django 5.0 on 2025-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_client_logo_file_client_logo_text_client_logo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='login_type',
            field=models.CharField(choices=[('mobile', 'mobile'), ('email', 'email')], default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
