# Generated by Django 4.2.25 on 2025-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_client_login_type_alter_client_logo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_password_login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='login_type',
            field=models.CharField(choices=[('phone', 'phone'), ('email', 'email')], default='email', max_length=50),
        ),
    ]
