# Generated by Django 4.2.25 on 2025-10-15 22:38

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('privacy_policy', 'Privacy policy'), ('terms_of_service', 'Terms of Service')], max_length=50, unique=True)),
                ('content_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content ar')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content en')),
            ],
            options={
                'verbose_name': 'Web View',
                'verbose_name_plural': 'Web Views',
                'ordering': ('-id',),
            },
        ),
    ]
