# Generated by Django 5.0 on 2025-09-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_lesson_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration in min (e.g., 12.5)', max_digits=5, null=True),
        ),
    ]
