# Generated by Django 4.2.25 on 2025-10-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_sequential',
            field=models.BooleanField(default=False, help_text='If True, students must complete lessons in order'),
        ),
    ]
