# Generated by Django 4.2.25 on 2025-10-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_has_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
