# Generated by Django 5.0 on 2025-12-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_lesson_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('article', 'Article'), ('exam', 'Exam'), ('material', 'Material'), ('assessment', 'Assessment')], default='video', max_length=20),
        ),
    ]
