# Generated by Django 4.2.25 on 2025-10-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreview',
            name='tell_about_your_experience',
        ),
    ]
