# Generated by Django 5.0 on 2025-12-14 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_assessmentquestion_user_assessment_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentquestion',
            old_name='correct_answer',
            new_name='correct_answer_key',
        ),
        migrations.RenameField(
            model_name='assessmentquestion',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_joined',
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='account.assessmentquestion'),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
