# Generated by Django 5.0 on 2025-12-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_correct_answer_assessmentquestion_correct_answer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assessment_advanced_tips',
            field=models.JSONField(blank=True, default=list, help_text='نصائح متقدمة من Gemini', null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='explanation_ar',
            field=models.TextField(blank=True, help_text='شرح مفصل للإجابة من Gemini', null=True),
        ),
    ]
