# Generated by Django 5.0 on 2025-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_assessment_advanced_tips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assessment_advanced_tips',
            field=models.JSONField(blank=True, default=None, help_text='نصائح متقدمة من Gemini', null=True),
        ),
    ]
