# Generated by Django 4.2.25 on 2025-10-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('exam', 'Exam'), ('quiz', 'Quiz'), ('assessment', 'Assessment')], default='quiz', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='type',
            field=models.CharField(choices=[('exam', 'Exam'), ('quiz', 'Quiz'), ('assessment', 'Assessment')], default='quiz', max_length=10),
        ),
    ]
