# Generated by Django 5.0 on 2025-09-26 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VotingCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IraqObserverApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=150)),
                ('residential_area', models.CharField(max_length=150)),
                ('nearest_voting_center', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('voter_card_number', models.CharField(max_length=25)),
                ('has_previous_shams_participation', models.BooleanField()),
                ('previous_training_topics', models.TextField(blank=True)),
                ('experience_level', models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('weak', 'Weak')], max_length=20)),
                ('political_neutrality_confirmation', models.BooleanField()),
                ('attendance_commitment_confirmation', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observer_applications', to='iraq_form.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IraqFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(max_length=150)),
                ('third_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('polling_center_number', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voting_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='iraq_form.votingcenter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
