# Generated by Django 5.0 on 2025-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraq_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iraqformsubmission',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
