# Generated by Django 4.2.25 on 2025-10-07 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iraq_form', '0002_iraqformsubmission_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='IraqFormAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('action_type', models.CharField(choices=[('page_visit', 'زيارة الصفحة'), ('form_submission', 'تقديم النموذج')], max_length=20, verbose_name='نوع العملية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إحصائيات فورم العراق',
                'verbose_name_plural': 'إحصائيات فورم العراق',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='iraq_form_i_ip_addr_ac313a_idx'), models.Index(fields=['action_type', 'created_at'], name='iraq_form_i_action__fefb71_idx'), models.Index(fields=['created_at'], name='iraq_form_i_created_a263ed_idx')],
            },
        ),
    ]
