# Generated by Django 4.2.25 on 2025-10-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraq_form', '0003_iraqformanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='iraqformanalytics',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المصدر'),
        ),
    ]
